export const initialTasks = [
  {
    id: "read",
    title: "读 20 分钟，记录一个启发",
    category: "学习成长",
    time: "早间",
    duration: "20 分钟",
    done: true,
  },
  {
    id: "focus",
    title: "专注完成一件重要的事",
    category: "工作提升",
    time: "上午",
    duration: "45 分钟",
    done: false,
  },
  {
    id: "walk",
    title: "出门走走，让身体充充电",
    category: "健康生活",
    time: "午后",
    duration: "30 分钟",
    done: false,
  },
  {
    id: "review",
    title: "留一点时间，回顾今天",
    category: "自我探索",
    time: "晚间",
    duration: "10 分钟",
    done: false,
  },
];
export const goals = [
  {
    title: "让阅读成为日常",
    description: "每天留 20 分钟，和新想法相遇。",
    category: "学习成长",
    value: 7,
    total: 20,
    unit: "天",
    color: "green",
  },
  {
    title: "找回身体的活力",
    description: "每周运动 3 次，保持自己的节奏。",
    category: "健康生活",
    value: 2,
    total: 3,
    unit: "次",
    color: "orange",
  },
  {
    title: "给自己一个新技能",
    description: "专注练习，把好奇变成能力。",
    category: "工作提升",
    value: 3,
    total: 10,
    unit: "次",
    color: "purple",
  },
];
